---
Name: myproject
---

DirectLease\Auth0\ApiController:
  client_id: 'Your Auth0 application client id'
  m2m_client_id: 'Your Auth0 M2M application client id'
  client_secret: 'Your Auth0 application client secret'
  m2m_client_secret: 'Your auth0 M2M application client secret'
  domain: 'Your Auth0 application domain'
  redirect_uri: 'The Auth0 callback url, default is /auth/callback'
  scope: 'The scope of the user object you get back - openid email profile'
  default_mailaddress: 'The emailaddress you want to use for your default SilverStripe user'
  namespace: 'The namespace you use in your auth0 application rules'
  persisent_login: 'Do you want to use the persistant login from SilverStripe? needs to be true or false (boolean)'
  multi_locale: false

DirectLease\Auth0\Extensions\MemberExtension:
  properties:
    OptionalDefaultFields: 'Default Value'

DirectLease\Auth0\Verified:
  verification_uri: 'The url you want to redirect to if member is not verified yet'
